---

- name: Deploy HBase
  become: yes
  hosts: hadoopnodes
  roles:
    - role: java
    - role: hbase_install
      hbase_version: 1.2.0   # hbase 1.2.X on hadoop 2.7.1+ is supported
    - role: hbase_configure
